### PR TITLE
django 3.0 compatibility

### PR DESCRIPTION
**Pull request by jerzyk**
django 3.0 removed @six@ from @django.utils@

### CODE REVIEW

**Comment by marco-silva0000** [comment]
closes #45

**Comment by thinders-accenture** [comment]
Hi! Any reason this can't be merged?

**Comment by jpadilla** [comment]
Thanks for this. What would really help move this next release forward is actually dropping support for Python 2 all together. The only reason we need six is to have easier compat between Python 2 and Python 3.

https://github.com/jpadilla/django-rest-framework-xml/issues/45#issuecomment-565111475

**Comment by jpadilla** [comment]
Closed by #53

**Pull request closed without merging**
